### ISSUE TITLE
Would appreciate headers "Access-Control-Allow-Origin" configuration

### ISSUE THREAD

**Issue by kzurell** [dataarts/tailbone#23]
Trying to use tailbone within Hangout App, which parses everything from a different host for some reason. I'm having to sprinkle Allow Origin headers throughout core.

**Comment by 796289** [comment]
I have tailbone Restful server run on localhost:8080 and I have another project run on localhost:8001. I tried to use tailbone/proxy, turned on tailbone_CORS = True but still fail to send ajax request from 8001 to 8080. Could you give me an advice?

**Comment by doug** [comment]
The dev app server started adding Access-Control-Allow-Origin and tailbone was adding to it rather than replacing the header and you cannot have two. This update fixes the issue: https://github.com/dataarts/tailbone/commit/24a96926146f0a6e936d9b27553d746faeaf24e8.

Thanks!
